# Environment variable names for configuration
STORAGE_TYPE="STORAGE_TYPE"
KAFKA_BOOTSTRAP_SERVERS="KAFKA_BOOTSTRAP_SERVERS"
KAFKA_TOPIC="KAFKA_TOPIC"
POSTGRES_CONNECTION_STRING="POSTGRES_CONNECTION_STRING"
AGGREGATION_INTERVAL="AGGREGATION_INTEVAL"
VABUS_URL="VABUS_URL"
DEFAULT_VABUS_URL="http://localhost:8000"
